SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `roda_expresso`
--
USE roda_expresso;

-- DROP das tabelas (já fornecido por ti)
DROP TABLE IF EXISTS avaliacoes;
DROP TABLE IF EXISTS horariostransporte;
DROP TABLE IF EXISTS ofertatransporte;
DROP TABLE IF EXISTS utilizador;
DROP TABLE IF EXISTS condutor;
DROP TABLE IF EXISTS transporte;
DROP TABLE IF EXISTS dominiospermitidos;
DROP TABLE IF EXISTS tipoutilizador;

--
-- Banco de dados: `roda_expresso`
--
DROP DATABASE IF EXISTS `roda_expresso`;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;